# Generated by Django 5.0.4 on 2024-04-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JustSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('bio2', models.CharField(blank=True, max_length=255, null=True)),
                ('bio3', models.CharField(blank=True, max_length=255, null=True)),
                ('bio4', models.CharField(blank=True, max_length=255, null=True)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productImage2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productImage3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productImage4', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productImage5', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productImage6', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productImage7', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productImage8', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('productImage9', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('createdAT', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isOnFrontPage', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ['createdAT'],
            },
        ),
    ]
