# Generated by Django 5.0.4 on 2024-04-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_justsending_bio_alter_justsending_bio2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fullName', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pinCode', models.IntegerField()),
                ('phoneNumber2', models.IntegerField()),
                ('textNote', models.CharField(blank=True, max_length=955, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ManyToManyField(related_name='coupon', to='core.justsending')),
            ],
            options={
                'verbose_name_plural': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='OrderItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.justsending')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstVariant', models.CharField(blank=True, max_length=255, null=True)),
                ('secondVariant', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdVariant', models.CharField(blank=True, max_length=255, null=True)),
                ('fourthVariant', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ManyToManyField(related_name='variant', to='core.justsending')),
            ],
            options={
                'verbose_name_plural': 'SizeVariant',
            },
        ),
    ]
