# Generated by Django 5.0.4 on 2024-04-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_coupon_orderitemproduct_sizevariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorClassVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('varianImg1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('varianImg2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('varianImg3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('varianImg4', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('varianImg5', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('varianImg6', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('varianImg7', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('varianImg8', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('varianImg9', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'ColorClassVariant',
            },
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('varianImg', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('imgsHere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorclassvariant', to='core.colorclassvariant')),
                ('product', models.ManyToManyField(related_name='colorvariant', to='core.justsending')),
            ],
            options={
                'verbose_name_plural': 'ColorVariant',
            },
        ),
    ]
