# Generated by Django 5.0.4 on 2024-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_colorclassvariant_colorvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('SecondColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('fourthColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('fifthColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('sixthColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('seventhColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('eightColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('ninethColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('tehnthColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('eleventhColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('twelvethColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('threeteenColorType', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Default Color',
            },
        ),
        migrations.CreateModel(
            name='DefaultProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('SecondProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('fourthProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('fifthProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('sixthProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('seventhProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('eightProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('ninethProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('tehnthProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('eleventhProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('twelvethProductType', models.CharField(blank=True, max_length=255, null=True)),
                ('threeteenProductType', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Default Product Type',
            },
        ),
        migrations.CreateModel(
            name='DefaultSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('SecondSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('fourthSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('fifthSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('sixthSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('seventhSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('eightSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('ninethSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('tehnthSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('eleventhSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('twelvethSizeName', models.CharField(blank=True, max_length=255, null=True)),
                ('threeteenSizeName', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Default Size',
            },
        ),
    ]
