# Generated by Django 5.0.4 on 2024-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_defaultcolor_defaultproducttype_defaultsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='justsending',
            name='defaultColors',
            field=models.ManyToManyField(related_name='defaultColors', to='core.defaultcolor'),
        ),
        migrations.AddField(
            model_name='justsending',
            name='defaultProductTypes',
            field=models.ManyToManyField(related_name='defaultProductTypes', to='core.defaultproducttype'),
        ),
        migrations.AddField(
            model_name='justsending',
            name='defaultSizes',
            field=models.ManyToManyField(related_name='defaultSizes', to='core.defaultsize'),
        ),
    ]
