# Generated by Django 5.0.4 on 2024-04-22 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_justsending_defaultcolors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justsending',
            name='defaultSizes',
        ),
        migrations.AddField(
            model_name='justsending',
            name='defaultSizes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='defaultSizes', to='core.defaultsize'),
        ),
    ]
