# Generated by Django 5.0.4 on 2024-04-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_justsending_defaultsizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justsending',
            name='defaultSizes',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defaultSizes', to='core.defaultsize'),
        ),
    ]
