# Generated by Django 5.0.4 on 2024-04-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_justsending_defaultsizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justsending',
            name='defaultSizes',
        ),
        migrations.AddField(
            model_name='justsending',
            name='defaultSizes',
            field=models.ManyToManyField(related_name='defaultSizes', to='core.defaultsize'),
        ),
    ]
