# Generated by Django 5.0.4 on 2024-04-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_justsending_defaultsizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justsending',
            name='defaultSizes',
        ),
        migrations.AddField(
            model_name='justsending',
            name='defaultSizes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.defaultsize'),
        ),
    ]
