# Generated by Django 5.0.4 on 2024-04-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_justsending_defaultcolors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('SecondColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('fourthColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('fifthColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('sixthColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('seventhColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('eightColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('ninethColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('tehnthColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('eleventhColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('twelvethColorType', models.CharField(blank=True, max_length=255, null=True)),
                ('threeteenColorType', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Default Color',
            },
        ),
        migrations.RemoveField(
            model_name='justsending',
            name='colors',
        ),
        migrations.AddField(
            model_name='justsending',
            name='color',
            field=models.ManyToManyField(to='core.defaultcolor'),
        ),
    ]
