# Generated by Django 5.0.4 on 2024-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_defaultcolor_remove_justsending_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justsending',
            name='color',
        ),
        migrations.AddField(
            model_name='justsending',
            name='colors',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], default='red', max_length=50),
        ),
        migrations.DeleteModel(
            name='DefaultColor',
        ),
    ]
