# Generated by Django 5.0.4 on 2024-04-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_justsending_colors_justsending_defaultsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='justsending',
            name='defaultproductVar',
            field=models.CharField(choices=[('Adults', 'Adults'), ('Kids', 'Kids'), ('Accessories', 'Accessories')], default='', max_length=255),
        ),
    ]
