# Generated by Django 5.0.4 on 2024-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_justsending_defaultproductvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justsending',
            name='defaultSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('8s', '8'), ('10s', '10'), ('12s', '12'), ('14s', '14'), ('16s', '16'), ('One Size', 'One Size')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='justsending',
            name='defaultcolors',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Camo', 'Camo'), ('Green', 'Green'), ('Gray', 'Gray'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='justsending',
            name='defaultproductType',
            field=models.CharField(choices=[('Adapt', 'Adapt'), ('Boots & Mittens', 'Boots & Mittens'), ('Dryrobe® Advance', 'Dryrobe® Advance'), ('Headwear', 'Headwear'), ('Lite', 'Lite'), ('Towel Change Robes', 'Towel Change Robes'), ('Pink', 'Pink'), ('Purple', 'Purple')], default='', max_length=50),
        ),
    ]
