# Generated by Django 5.0.4 on 2024-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_justsending_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemproduct',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
