# Generated by Django 5.0.4 on 2024-04-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_orderitemproduct_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_colors', to='core.colorvariant'),
        ),
    ]
