# Generated by Django 5.0.4 on 2024-04-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_orderitemproduct_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justsending',
            name='productImage2',
        ),
        migrations.RemoveField(
            model_name='justsending',
            name='productImage3',
        ),
        migrations.RemoveField(
            model_name='justsending',
            name='productImage4',
        ),
        migrations.RemoveField(
            model_name='justsending',
            name='productImage5',
        ),
        migrations.RemoveField(
            model_name='justsending',
            name='productImage6',
        ),
        migrations.RemoveField(
            model_name='justsending',
            name='productImage7',
        ),
        migrations.RemoveField(
            model_name='justsending',
            name='productImage8',
        ),
        migrations.RemoveField(
            model_name='justsending',
            name='productImage9',
        ),
    ]
